# Generated by Django 6.0.3 on 2026-05-12 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('razao_social', models.CharField(max_length=255)),
                ('responsavel', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_unidade', models.CharField(max_length=255)),
                ('coordenador', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_submissao', models.DateTimeField(auto_now_add=True)),
                ('arquivo_original', models.BinaryField(blank=True, null=True)),
                ('status', models.CharField(choices=[('RECEBIDO', 'Recebido'), ('PROCESSANDO', 'Processando'), ('INVALIDO_PENDENTE', 'Inválido pendente'), ('VALIDADO_OK', 'Validado OK'), ('APROVADO_FINAL', 'Aprovado final')], default='RECEBIDO', max_length=20)),
                ('score_conformidade', models.FloatField(default=0.0)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='app.empresa')),
                ('instituicao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos', to='app.instituicao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='app.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='SistemaValidador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sistema_validador', to='app.contrato')),
            ],
        ),
    ]
