# Generated by Django 6.0.4 on 2026-05-22 11:42

import django.db.models.deletion
from django.db import migrations, models


REGRAS_PADRAO = [
    {
        'codigo': 'CARGA_DIARIA',
        'nome': 'Carga horaria diaria',
        'descricao': 'Carga horaria diaria nao deve ultrapassar 6 horas.',
        'severidade_padrao': 'ERRO',
    },
    {
        'codigo': 'CARGA_SEMANAL',
        'nome': 'Carga horaria semanal',
        'descricao': 'Carga horaria semanal nao deve ultrapassar 30 horas.',
        'severidade_padrao': 'ERRO',
    },
    {
        'codigo': 'SEGURO',
        'nome': 'Seguro obrigatorio',
        'descricao': 'Contrato deve informar seguro contra acidentes pessoais.',
        'severidade_padrao': 'ERRO',
    },
    {
        'codigo': 'SUPERVISOR',
        'nome': 'Supervisor da empresa',
        'descricao': 'Contrato deve indicar supervisor da parte concedente.',
        'severidade_padrao': 'PENDENCIA',
    },
    {
        'codigo': 'PROFESSOR_ORIENTADOR',
        'nome': 'Professor orientador',
        'descricao': 'Estagio deve ter acompanhamento institucional.',
        'severidade_padrao': 'PENDENCIA',
    },
    {
        'codigo': 'ATIVIDADES',
        'nome': 'Plano de atividades',
        'descricao': 'Atividades devem estar descritas para analise de compatibilidade.',
        'severidade_padrao': 'PENDENCIA',
    },
    {
        'codigo': 'BOLSA',
        'nome': 'Bolsa-auxilio',
        'descricao': 'Estagio nao obrigatorio exige bolsa-auxilio.',
        'severidade_padrao': 'ERRO',
    },
    {
        'codigo': 'AUXILIO_TRANSPORTE',
        'nome': 'Auxilio-transporte',
        'descricao': 'Estagio nao obrigatorio exige auxilio-transporte.',
        'severidade_padrao': 'ERRO',
    },
    {
        'codigo': 'DURACAO_MAXIMA',
        'nome': 'Duracao maxima',
        'descricao': 'Contrato nao deve ultrapassar 2 anos na mesma empresa.',
        'severidade_padrao': 'ERRO',
    },
]


def criar_regras_padrao(apps, schema_editor):
    RegraValidacao = apps.get_model('app', 'RegraValidacao')
    for regra in REGRAS_PADRAO:
        RegraValidacao.objects.get_or_create(codigo=regra['codigo'], defaults=regra)


def remover_regras_padrao(apps, schema_editor):
    RegraValidacao = apps.get_model('app', 'RegraValidacao')
    RegraValidacao.objects.filter(codigo__in=[regra['codigo'] for regra in REGRAS_PADRAO]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegraValidacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.TextField()),
                ('severidade_padrao', models.CharField(choices=[('INFO', 'Informacao'), ('PENDENCIA', 'Pendencia'), ('ERRO', 'Erro')], default='ERRO', max_length=20)),
                ('ativa', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
        migrations.AddField(
            model_name='contrato',
            name='versao',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='status',
            field=models.CharField(choices=[('RECEBIDO', 'Recebido'), ('PROCESSANDO', 'Processando'), ('INVALIDO_PENDENTE', 'Invalido pendente'), ('VALIDADO_OK', 'Validado OK'), ('APROVADO_FINAL', 'Aprovado final'), ('REPROVADO', 'Reprovado')], default='RECEBIDO', max_length=20),
        ),
        migrations.CreateModel(
            name='AnaliseContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(choices=[('APROVADO', 'Aprovado'), ('PENDENTE', 'Pendente'), ('REPROVADO', 'Reprovado')], default='PENDENTE', max_length=20)),
                ('score_conformidade', models.FloatField(default=0.0)),
                ('dados_extraidos', models.JSONField(blank=True, default=dict)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analises', to='app.contrato')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Estagio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=120)),
                ('nivel_ensino', models.CharField(choices=[('SUPERIOR', 'Superior'), ('MEDIO', 'Medio'), ('PROFISSIONAL', 'Educacao profissional'), ('FUNDAMENTAL_EJA', 'Fundamental EJA')], default='SUPERIOR', max_length=20)),
                ('tipo_estagio', models.CharField(choices=[('OBRIGATORIO', 'Obrigatorio'), ('NAO_OBRIGATORIO', 'Nao obrigatorio')], max_length=20)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('carga_horaria_diaria', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('carga_horaria_semanal', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('atividades', models.TextField(blank=True)),
                ('supervisor_nome', models.CharField(blank=True, max_length=120)),
                ('supervisor_formacao', models.CharField(blank=True, max_length=120)),
                ('professor_orientador', models.CharField(blank=True, max_length=120)),
                ('seguro_apolice', models.CharField(blank=True, max_length=80)),
                ('bolsa_auxilio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('auxilio_transporte', models.BooleanField(default=False)),
                ('plano_atividades', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estagios', to='app.empresa')),
                ('instituicao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estagios', to='app.instituicao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estagios', to='app.usuario')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='contrato',
            name='estagio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos', to='app.estagio'),
        ),
        migrations.CreateModel(
            name='ParecerInstitucional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=120)),
                ('aprovado', models.BooleanField()),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pareceres', to='app.contrato')),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pareceres', to='app.instituicao')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Pendencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_regra', models.CharField(max_length=50)),
                ('severidade', models.CharField(choices=[('INFO', 'Informacao'), ('PENDENCIA', 'Pendencia'), ('ERRO', 'Erro')], max_length=20)),
                ('mensagem', models.TextField()),
                ('resolvida', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('analise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pendencias', to='app.analisecontrato')),
                ('regra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pendencias', to='app.regravalidacao')),
            ],
            options={
                'ordering': ['severidade', 'codigo_regra'],
            },
        ),
        migrations.CreateModel(
            name='RelatorioConformidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('APROVADO', 'Aprovado'), ('PENDENTE', 'Pendente'), ('REPROVADO', 'Reprovado')], max_length=20)),
                ('conteudo', models.TextField()),
                ('gerado_em', models.DateTimeField(auto_now_add=True)),
                ('analise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='relatorio', to='app.analisecontrato')),
            ],
        ),
        migrations.RunPython(criar_regras_padrao, remover_regras_padrao),
    ]
