# Generated by Django 6.0.4 on 2026-05-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_regravalidacao_contrato_versao_alter_contrato_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='arquivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='contratos/'),
        ),
    ]
