# Generated by Django 6.0.4 on 2026-06-12 04:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def criar_regra_compatibilidade(apps, schema_editor):
    RegraValidacao = apps.get_model('app', 'RegraValidacao')
    RegraValidacao.objects.get_or_create(
        codigo='ATIVIDADES_COMPATIBILIDADE',
        defaults={
            'nome': 'Compatibilidade de atividades',
            'descricao': 'Atividades devem ser compativeis com o curso ou passar por revisao manual.',
            'severidade_padrao': 'PENDENCIA',
        },
    )


def remover_regra_compatibilidade(apps, schema_editor):
    RegraValidacao = apps.get_model('app', 'RegraValidacao')
    RegraValidacao.objects.filter(codigo='ATIVIDADES_COMPATIBILIDADE').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_contrato_arquivo_pdf'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='arquivo_original',
        ),
        migrations.AddField(
            model_name='usuario',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='VersaoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo_pdf', models.FileField(upload_to='contratos/versoes/')),
                ('numero_versao', models.PositiveIntegerField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versoes_pdf', to='app.contrato')),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versoes_contrato_enviadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-numero_versao'],
                'unique_together': {('contrato', 'numero_versao')},
            },
        ),
        migrations.RunPython(criar_regra_compatibilidade, remover_regra_compatibilidade),
    ]
